// CSV/JSON inspection export. Reads from the derived `production_problems`
// table (the deliverable), so run `build` first. Output is for eyeballing /
// spot-checking — the real consumer is production_problems itself.
import { dirname } from "node:path";
import { mkdirSync } from "node:fs";
import { RATING_POLICY } from "../rating_policy.js";
import { matchRule, computeSeed } from "./ratingSeed.js";

function sanitizeStringCSV(content) {
    content = content.replace(/\r\n/g, "\n");
    if (/[",\n\r]/.test(content)) {
        return `"${content.replace(/"/g, '""')}"`;
    }
    return content;
}

function JSONToCSV(data) {
    if (data.length === 0) return "";
    const keys = Object.keys(data[0]);
    let text = keys.join(",") + "\n";
    for (let i = 0; i < data.length; i++) {
        for (let j = 0; j < keys.length; j++) {
            const d = data[i][keys[j]];
            if (Array.isArray(d)) {
                text += `"[${d.map((a) => `""${String(a).replace(/\\/g, "\\\\")}""`).join(",")}]"`;
            } else if (d != null) {
                text += typeof d === "string" ? sanitizeStringCSV(d) : d;
            }
            if (j < keys.length - 1) text += ",";
        }
        if (i < data.length - 1) text += "\n";
    }
    return text;
}

// Writes scrape_data/{series,tests,production_problems}.csv plus a JSON copy of
// the problems. Returns the number of exported problems.
export async function exportProductionCSV(db, outDir = "scrape_data") {
    const problems = db
        .query(
            `
        SELECT pp.test_id, pp.n, pp.aops_id, pp.statement, pp.choices,
               pp.answer_index, pp.official_solutions,
               pp.topic, pp.tags, pp.is_computational, pp.difficulty,
               pp.quality, pp.verified, pp.notes,
               t.name AS test_name, t.year AS test_year,
               s.name AS series_name, s.is_official
        FROM production_problems pp
        JOIN tests t ON pp.test_id = t.id
        JOIN series s ON t.series_id = s.id
        ORDER BY s.name, t.year, t.name, pp.n
    `,
        )
        .all();

    if (problems.length === 0) {
        console.warn(
            "production_problems is empty — run `build` before `export`.",
        );
        return 0;
    }

    const tests = db
        .query(
            `
        SELECT t.*, s.name AS series_name, s.is_official
        FROM tests t JOIN series s ON t.series_id = s.id
        ORDER BY s.name, t.year, t.name
    `,
        )
        .all();

    const series = db.query(`SELECT * FROM series ORDER BY name`).all();

    await Bun.write(`${outDir}/series.csv`, JSONToCSV(series));
    await Bun.write(`${outDir}/tests.csv`, JSONToCSV(tests));
    await Bun.write(
        `${outDir}/production_problems.json`,
        JSON.stringify(problems, null, 2),
    );
    await Bun.write(`${outDir}/production_problems.csv`, JSONToCSV(problems));

    return problems.length;
}

const SQL_EXPORT_SCHEMA = `
DROP TABLE IF EXISTS problems CASCADE;
DROP TABLE IF EXISTS tests CASCADE;
DROP TABLE IF EXISTS series CASCADE;

CREATE TABLE series (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL UNIQUE,
  aops_id INTEGER DEFAULT -1,
  is_official BOOLEAN NOT NULL DEFAULT FALSE CHECK (is_official IN (FALSE, TRUE))
);

CREATE TABLE tests (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  series_id INTEGER REFERENCES series(id),
  name TEXT NOT NULL,
  section INTEGER NOT NULL DEFAULT -1,
  year INTEGER,
  aops_category_id TEXT,
  type TEXT,
  is_computational BOOLEAN NOT NULL DEFAULT FALSE CHECK (is_computational IN (FALSE, TRUE)),
  difficulty INTEGER DEFAULT 0,
  quality INTEGER DEFAULT 0,
  aops_url TEXT GENERATED ALWAYS AS ('https://artofproblemsolving.com/community/c' || aops_category_id) STORED,
  UNIQUE(aops_category_id, section)
);

CREATE TABLE problems (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  test_id INTEGER REFERENCES tests(id) ON DELETE CASCADE,
  n INTEGER NOT NULL,
  aops_id INTEGER,
  statement TEXT,
  choices TEXT[],
  answer_index INTEGER DEFAULT -1,
  official_solutions TEXT[],
  topic TEXT,
  tags TEXT[],
  is_computational BOOLEAN NOT NULL DEFAULT FALSE CHECK (is_computational IN (FALSE, TRUE)),
  difficulty INTEGER DEFAULT 0,
  quality INTEGER DEFAULT 0,
  verified BOOLEAN NOT NULL DEFAULT FALSE CHECK (verified IN (FALSE, TRUE)),
  notes TEXT,
  built_at TEXT DEFAULT (CURRENT_TIMESTAMP::TEXT),
  UNIQUE(test_id, n)
);
`.trim();

const SQL_EXPORT_TABLES = [
    {
        name: "series",
        columns: ["id", "name", "aops_id", "is_official"],
        select: `
            SELECT id, name, aops_id, is_official
            FROM series
            ORDER BY id
        `,
    },
    {
        name: "tests",
        columns: [
            "id",
            "series_id",
            "name",
            "section",
            "year",
            "aops_category_id",
            "type",
            "is_computational",
            "difficulty",
            "quality",
        ],
        select: `
            SELECT id, series_id, name, section, year, aops_category_id,
                   type, is_computational, difficulty, quality
            FROM tests
            ORDER BY id
        `,
    },
    {
        name: "problems",
        sourceName: "production_problems",
        columns: [
            "id",
            "test_id",
            "n",
            "aops_id",
            "statement",
            "choices",
            "answer_index",
            "official_solutions",
            "topic",
            "tags",
            "is_computational",
            "difficulty",
            "quality",
            "verified",
            "notes",
            "built_at",
        ],
        select: `
            SELECT id, test_id, n, aops_id, statement, choices, answer_index,
                   official_solutions, topic, tags, is_computational,
                   difficulty, quality, verified, notes, built_at
            FROM production_problems
            ORDER BY id
        `,
    },
];

function quoteIdent(identifier) {
    return `"${identifier.replace(/"/g, '""')}"`;
}

function sqlString(value) {
    return `'${String(value).replace(/'/g, "''")}'`;
}

function toTextArrayLiteral(value) {
    if (value === null || value === undefined) {
        return null;
    }

    let items = value;
    if (typeof value === "string") {
        try {
            items = JSON.parse(value);
        } catch (e) {
            items = value.startsWith("{") && value.endsWith("}") ? value : null;
        }
    }

    if (typeof items === "string") {
        return items;
    }
    if (!Array.isArray(items)) {
        return null;
    }

    const escapedItems = items.map((item) => {
        if (item === null || item === undefined) {
            return "NULL";
        }
        const escaped = String(item).replace(/\\/g, "\\\\").replace(/"/g, '\\"');
        return `"${escaped}"`;
    });
    return `{${escapedItems.join(",")}}`;
}

function sqlValue(value, column) {
    if (value === null || value === undefined) return "NULL";
    if (
        column === "is_official" ||
        column === "is_computational" ||
        column === "verified"
    ) {
        return value ? "TRUE" : "FALSE";
    }
    if (column === "choices" || column === "tags") {
        return `${sqlString(value)}::TEXT[]`;
    }
    if (column === "official_solutions") {
        const arrayLiteral = toTextArrayLiteral(value);
        return arrayLiteral === null ? "NULL" : `${sqlString(arrayLiteral)}::TEXT[]`;
    }
    if (typeof value === "number") return String(value);
    return sqlString(value);
}

function insertStatements(table, rows) {
    if (rows.length === 0) return `-- ${table.name}: 0 rows`;

    const columnSql = table.columns.map(quoteIdent).join(", ");
    const values = rows
        .map(
            (row) =>
                `(${table.columns
                    .map((column) => sqlValue(row[column], column))
                    .join(", ")})`,
        )
        .join(",\n");

    return `INSERT INTO ${quoteIdent(table.name)} (${columnSql}) VALUES\n${values};`;
}

// ---------------------------------------------------------------------------
// Staging export for the ProblemCloud content-sync merge.
//
// Unlike exportProductionSQL (which DROPs + reloads and so wipes user data and
// renumbers ids), this emits a DATA-ONLY, non-destructive load into the cloud's
// _import_* staging tables. The cloud then runs public.sync_scraped_content(),
// which upserts on `sync_key` — preserving every problem id (and the user
// submissions/feedback FKs into it) and every curator edit. See
// problem-cloud/supabase/schemas/content_sync.sql.
//
// The sync_key is the stable cross-database identity. It MUST match the SQL
// formula in content_sync.sql byte-for-byte: delimiter chr(31) (U+001F), raw
// values, no slug/case-folding.
const SYNC_KEY_DELIM = "\x1f"; // U+001F unit separator == SQL chr(31)

// aops-sourced tests key on (aops_category_id, section); PDF/manual-only tests
// (no aops_category_id) fall back to (series_name, year, name, section).
function testSyncKey(row) {
    const d = SYNC_KEY_DELIM;
    if (row.aops_category_id != null) {
        return `aops${d}${row.aops_category_id}${d}${row.section}`;
    }
    const series = row.series_name ?? "";
    const year = row.year == null ? "" : String(row.year);
    return `manual${d}${series}${d}${year}${d}${row.name}${d}${row.section}`;
}

function problemSyncKey(testKey, n) {
    const d = SYNC_KEY_DELIM;
    return `${testKey}${d}n${d}${n}`;
}

const STAGING_TABLES = {
    series: {
        name: "_import_series",
        columns: ["name", "aops_id", "is_official"],
    },
    tests: {
        name: "_import_tests",
        columns: [
            "sync_key",
            "series_name",
            "name",
            "year",
            "aops_category_id",
            "section",
            "type",
            "is_computational",
            "difficulty",
            "quality",
        ],
    },
    problems: {
        name: "_import_problems",
        columns: [
            "sync_key",
            "test_sync_key",
            "n",
            "aops_id",
            "statement",
            "choices",
            "answer_index",
            "official_solutions",
            "topic",
            "tags",
            "is_computational",
            "difficulty",
            "quality",
            "verified",
            "notes",
        ],
    },
};

// Like insertStatements, but schema-qualifies the target as public.<table>
// (the staging tables live in public; the merge functions reference them so).
function stagingInsert(table, rows) {
    if (rows.length === 0) return `-- public.${table.name}: 0 rows`;
    const columnSql = table.columns.map(quoteIdent).join(", ");
    const values = rows
        .map(
            (row) =>
                `(${table.columns
                    .map((column) => sqlValue(row[column], column))
                    .join(", ")})`,
        )
        .join(",\n");
    return `INSERT INTO public.${quoteIdent(table.name)} (${columnSql}) VALUES\n${values};`;
}

// Writes a data-only staging load for the content-sync merge: TRUNCATE the
// _import_* tables, reload them from series/tests/production_problems (with a
// computed sync_key on each row), all in one transaction. Run this file against
// the cloud, then `select * from sync_scraped_content(true|false)`.
export async function exportStagingSQL(
    db,
    outFile = "scrape_data/staging_load.sql",
) {
    const series = db
        .query(`SELECT name, aops_id, is_official FROM series ORDER BY name`)
        .all();

    // Tests must resolve to a series (the cloud requires series_name and the
    // merge aborts on an unknown series), so INNER JOIN drops seriesless tests.
    const tests = db
        .query(
            `
        SELECT t.id, s.name AS series_name, t.name, t.year, t.aops_category_id,
               t.section, t.type, t.is_computational, t.difficulty, t.quality
        FROM tests t JOIN series s ON t.series_id = s.id
        ORDER BY t.id
    `,
        )
        .all();

    const testKeyById = new Map();
    for (const t of tests) {
        t.sync_key = testSyncKey(t);
        testKeyById.set(t.id, t.sync_key);
    }

    const allProblems = db
        .query(
            `
        SELECT pp.test_id, pp.n, pp.aops_id, pp.statement, pp.choices,
               pp.answer_index, pp.official_solutions, pp.topic, pp.tags,
               pp.is_computational, pp.difficulty, pp.quality, pp.verified,
               pp.notes
        FROM production_problems pp
        ORDER BY pp.test_id, pp.n
    `,
        )
        .all();

    // Problems whose test was dropped above (no series) can't be synced.
    const problems = [];
    let orphaned = 0;
    for (const p of allProblems) {
        const testKey = testKeyById.get(p.test_id);
        if (testKey == null) {
            orphaned++;
            continue;
        }
        p.test_sync_key = testKey;
        p.sync_key = problemSyncKey(testKey, p.n);
        problems.push(p);
    }

    const parts = [
        "-- Generated by aops-scrape `sync-export`.",
        "-- Data-only, non-destructive staging load for the ProblemCloud",
        "-- content-sync merge. After running this, execute:",
        "--   select * from public.sync_scraped_content(true);   -- dry run",
        "--   select * from public.sync_scraped_content(false);  -- apply",
        "-- sync_key columns use a chr(31) (U+001F) delimiter; see content_sync.sql.",
        "",
        "BEGIN;",
        "TRUNCATE public._import_series, public._import_tests, public._import_problems;",
        "",
        "-- series",
        stagingInsert(STAGING_TABLES.series, series),
        "",
        "-- tests",
        stagingInsert(STAGING_TABLES.tests, tests),
        "",
        "-- problems",
        stagingInsert(STAGING_TABLES.problems, problems),
        "",
        "COMMIT;",
    ];

    mkdirSync(dirname(outFile), { recursive: true });
    await Bun.write(outFile, `${parts.join("\n")}\n`);

    return {
        file: outFile,
        counts: {
            series: series.length,
            tests: tests.length,
            problems: problems.length,
        },
        orphaned,
    };
}

// ---------------------------------------------------------------------------
// Rating seed export for ProblemCloud's public.problem_ratings.
//
// Walks production_problems, matches each test against the rating policy
// (rating_policy.js), spreads the rule's [lower, upper] band across the test by
// problem number `n`, and emits ONE idempotent `insert … on conflict` statement
// keyed by sync_key. Reuses the same testSyncKey/problemSyncKey/sqlString as the
// content-sync staging load, so the emitted keys are byte-identical (chr(31)
// delimiter) to what public.problems already stores.
//
// Modes (differ only in the on-conflict WHERE clause):
//   default             seed-then-lock: only rows still at the untouched default
//                       (attempts = 0 AND rating = 1500) are re-seeded.
//   { overwrite: true } full re-tune: WHERE dropped; every matched problem is
//                       re-seeded regardless of current state.
// In both modes, any write that actually changes `rating` resets `rd` to 350.
export async function exportRatingSeedsSQL(
    db,
    outFile = "scrape_data/seed_ratings.sql",
    options = {},
) {
    const overwrite = options.overwrite ?? false;
    const policy = options.policy ?? RATING_POLICY;

    // Same join as exportStagingSQL, so sync_keys match the synced content.
    const tests = db
        .query(
            `
        SELECT t.id, s.name AS series_name, t.name, t.year, t.aops_category_id,
               t.section, t.type
        FROM tests t JOIN series s ON t.series_id = s.id
        ORDER BY t.id
    `,
        )
        .all();

    const testKeyById = new Map();
    const testById = new Map();
    for (const t of tests) {
        testKeyById.set(t.id, testSyncKey(t));
        testById.set(t.id, t);
    }

    const problems = db
        .query(`SELECT test_id, n FROM production_problems ORDER BY test_id, n`)
        .all();

    // Group problems by test to get each test's own min_n/max_n.
    const byTest = new Map();
    for (const p of problems) {
        let g = byTest.get(p.test_id);
        if (!g) {
            g = { ns: [], minN: Infinity, maxN: -Infinity };
            byTest.set(p.test_id, g);
        }
        g.ns.push(p.n);
        if (p.n < g.minN) g.minN = p.n;
        if (p.n > g.maxN) g.maxN = p.n;
    }

    const seeds = []; // { sync_key, seed }
    const ruleCounts = new Map();
    let unmatchedTests = 0;
    for (const [testId, g] of byTest) {
        const test = testById.get(testId);
        const testKey = testKeyById.get(testId);
        if (test == null || testKey == null) continue; // seriesless test
        const rule = matchRule(test, policy);
        if (rule == null) {
            unmatchedTests++;
            continue;
        }
        ruleCounts.set(rule.id, (ruleCounts.get(rule.id) ?? 0) + g.ns.length);
        for (const n of g.ns) {
            seeds.push({
                sync_key: problemSyncKey(testKey, n),
                seed: computeSeed(rule, n, g.minN, g.maxN),
            });
        }
    }

    const mode = overwrite ? "OVERWRITE (full re-tune)" : "seed-then-lock (default)";
    const countLines = [...ruleCounts.entries()]
        .sort((a, b) => b[1] - a[1])
        .map(([id, c]) => `--   ${id}: ${c}`);
    const header = [
        "-- Generated by aops-scrape `seed-ratings-export`. Seeds public.problem_ratings.rating.",
        `-- Mode: ${mode}`,
        `-- ${seeds.length} problems seeded across ${byTest.size - unmatchedTests} tests` +
            ` (${unmatchedTests} tests unmatched).`,
        "-- Rule match counts:",
        ...(countLines.length ? countLines : ["--   (none)"]),
        "-- Run against the ProblemCloud DB as service_role/postgres:",
        `--   psql "$DB_URL" -f ${outFile}`,
    ];

    let body;
    if (seeds.length === 0) {
        body = ["", "-- No problems matched a rule; nothing to seed."];
    } else {
        const values = seeds
            .map((s) => `  (${sqlString(s.sync_key)}, ${s.seed})`)
            .join(",\n");
        // Default mode locks to untouched rows; overwrite drops the WHERE.
        const whereClause = overwrite
            ? ";"
            : "\n  where public.problem_ratings.attempts = 0" +
              "\n    and public.problem_ratings.rating   = 1500::real;";
        body = [
            "",
            "begin;",
            "",
            "insert into public.problem_ratings (problem_id, scope, rating, rd)",
            "select p.id, 'overall', v.seed::real, 350",
            "from (values",
            values,
            ") as v(sync_key, seed)",
            "join public.problems p on p.sync_key = v.sync_key",
            "on conflict (problem_id, scope) do update",
            "  set rating = excluded.rating,",
            "      rd     = case when public.problem_ratings.rating is distinct from excluded.rating",
            "                    then 350::real",
            "                    else public.problem_ratings.rd end,",
            "      updated_at = now()" + whereClause,
            "",
            "commit;",
        ];
    }

    mkdirSync(dirname(outFile), { recursive: true });
    await Bun.write(outFile, `${[...header, ...body].join("\n")}\n`);

    return {
        file: outFile,
        matched: seeds.length,
        unmatchedTests,
        ruleCounts: Object.fromEntries(ruleCounts),
        overwrite,
    };
}

// Writes a PostgreSQL-flavored SQL export for the deliverable tables. The
// production_problems table is emitted as `problems`; tests intentionally omit
// `section_name` but keep `section` for AoPS category uniqueness.
export async function exportProductionSQL(
    db,
    outFile = "scrape_data/production_export.sql",
    options = {},
) {
    const includeSchema = options.includeSchema ?? true;
    const includeInserts = options.includeInserts ?? true;
    const parts = [
        "-- Generated by aops-scrape.",
        "-- Source tables: series, tests, production_problems AS problems.",
    ];

    const counts = {};

    if (includeSchema) {
        parts.push("", SQL_EXPORT_SCHEMA);
    }

    if (includeInserts) {
        parts.push("", "BEGIN;");
        for (const table of SQL_EXPORT_TABLES) {
            const rows = db.query(table.select).all();
            counts[table.name] = rows.length;
            parts.push("", `-- ${table.name}`, insertStatements(table, rows));
        }
        parts.push("", "COMMIT;");
    } else {
        for (const table of SQL_EXPORT_TABLES) {
            const sourceName = table.sourceName ?? table.name;
            const { c } = db
                .query(`SELECT count(*) AS c FROM ${sourceName}`)
                .get();
            counts[table.name] = c;
        }
    }

    mkdirSync(dirname(outFile), { recursive: true });
    await Bun.write(outFile, `${parts.join("\n")}\n`);

    return {
        file: outFile,
        counts,
        includeSchema,
        includeInserts,
    };
}
